---
- name: Install Docker
  hosts: hosts
  become: true
  vars:
    docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes
        cache_valid_time: 3600
    - name: Install prerequisites
      apt: 
        name: "{{ docker_packages }}"
        state: present
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
        state: present
    - name: Update apt cache
      apt: 
        update_cache: yes
    - name: Install Docker
      apt: 
        name: docker-ce
        state: present
    - name: Ensure Docker service is running
      service: 
        name: docker
        state: started
        enabled: true
