---
- name: install nginx
  apt:
    name: nginx
    state: latest

- name: Create document root
  file:
    path: "/var/www/nginx/html"
    state: directory
    owner: "root"
    mode: '0755'

- name: copy index.html template
  template:
    src: "templates/index.html"
    dest: "/usr/share/nginx/html"
  notify: Reloaded nginx
  vars:
    type_of_webserver: nginx

- name: Reloaded Nginx
  service:
    name: nginx
    state: reloaded
    enabled: true